import "@/css/global.css";
import type { Metadata } from "next";
import Script from "next/script";
import { M_PLUS_Rounded_1c } from "next/font/google";

const balsamiqSans = M_PLUS_Rounded_1c({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="//unpkg.com/react-scan/dist/auto.global.js" />
      <body
        className={`${balsamiqSans.className} h-dvh w-full antialiased flex bg-snow overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
